// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaderBoardApi.Migrations
{
    [DbContext(typeof(LeaderBoardContext))]
    [Migration("20220316084149_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-preview.1.22076.6");

            modelBuilder.Entity("LeaderBoardApi.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeSecs")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bob",
                            TimeSecs = "3.01"
                        },
                        new
                        {
                            Id = 2,
                            Name = "John",
                            TimeSecs = "4.02"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Simon",
                            TimeSecs = "2.59"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
